name = "koleksi-dr-pinguinn"
compatibility_date = "2026-09-27"
compatibility_flags = [ "nodejs_compat" ]

# KV analytics (kode baca env.ANALYTICS_KV)
[[kv_namespaces]]
binding = "ANALYTICS_KV"
id = "8c809729ccd64e5da6e9cb7dd62fb40b"

# Alias nama dashboard (opsional, sama namespace)
[[kv_namespaces]]
binding = "DR_PINGUIN_ANALYTICS"
id = "8c809729ccd64e5da6e9cb7dd62fb40b"

# Poster video. File tetap ada setelah deploy.
[[r2_buckets]]
binding = "POSTERS"
bucket_name = "posters"
