import { DEFAULT_PAGE_SIZE } from "./types";
import type { PagedVideos, VideoCard, VideoDetail } from "./types";
import { findCategory } from "./categories";
import localCatalog from "./videos.json";
import streamtapeBatch from "./streamtape.json";
import streamtapeBatchSep25 from "./streamtape-batch-20260925.json";
import putarinBatch from "./putarin.json";
import postersMap from "./posters.json";
import latestVideos from "../../../data/videos-latest.json";
import latestPosters from "../../../data/latest-posters.json";
