/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KategoriRouteImport } from './routes/kategori'
import { Route as ApiDataRouteImport } from './routes/api/data'
import { Route as ApiTapeThumbRouteImport } from './routes/api/tape-thumb'
import { Route as WatchIdRouteImport } from './routes/watch.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriRoute = KategoriRouteImport.update({
  id: '/kategori',
  path: '/kategori',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataRoute = ApiDataRouteImport.update({
  id: '/api/data',
  path: '/api/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTapeThumbRoute = ApiTapeThumbRouteImport.update({
  id: '/api/tape-thumb',
  path: '/api/tape-thumb',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIdRoute = WatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kategori': typeof KategoriRoute
  '/api/data': typeof ApiDataRoute
  '/api/tape-thumb': typeof ApiTapeThumbRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kategori': typeof KategoriRoute
  '/api/data': typeof ApiDataRoute
  '/api/tape-thumb': typeof ApiTapeThumbRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kategori': typeof KategoriRoute
  '/api/data': typeof ApiDataRoute
  '/api/tape-thumb': typeof ApiTapeThumbRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kategori' | '/api/data' | '/api/tape-thumb' | '/watch/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kategori' | '/api/data' | '/api/tape-thumb' | '/watch/$id'
  id: '__root__' | '/' | '/kategori' | '/api/data' | '/api/tape-thumb' | '/watch/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KategoriRoute: typeof KategoriRoute
  ApiDataRoute: typeof ApiDataRoute
  ApiTapeThumbRoute: typeof ApiTapeThumbRoute
  WatchIdRoute: typeof WatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategori': {
      id: '/kategori'
      path: '/kategori'
      fullPath: '/kategori'
      preLoaderRoute: typeof KategoriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data': {
      id: '/api/data'
      path: '/api/data'
      fullPath: '/api/data'
      preLoaderRoute: typeof ApiDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tape-thumb': {
      id: '/api/tape-thumb'
      path: '/api/tape-thumb'
      fullPath: '/api/tape-thumb'
      preLoaderRoute: typeof ApiTapeThumbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$id': {
      id: '/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof WatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KategoriRoute: KategoriRoute,
  ApiDataRoute: ApiDataRoute,
  ApiTapeThumbRoute: ApiTapeThumbRoute,
  WatchIdRoute: WatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
