/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KategoriRouteImport } from './routes/kategori'
import { Route as ApiDataRouteImport } from './routes/api/data'
import { Route as ApiEmbedThumbRouteImport } from './routes/api/embed-thumb'
import { Route as ApiPuterinThumbRouteImport } from './routes/api/puterin-thumb'
import { Route as ApiTapeThumbRouteImport } from './routes/api/tape-thumb'
import { Route as ApiTelegramRouteImport } from './routes/api/telegram'
import { Route as VIdRouteImport } from './routes/v.$id'
import { Route as WatchIdRouteImport } from './routes/watch.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriRoute = KategoriRouteImport.update({
  id: '/kategori',
  path: '/kategori',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataRoute = ApiDataRouteImport.update({
  id: '/api/data',
  path: '/api/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmbedThumbRoute = ApiEmbedThumbRouteImport.update({
  id: '/api/embed-thumb',
  path: '/api/embed-thumb',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPuterinThumbRoute = ApiPuterinThumbRouteImport.update({
  id: '/api/puterin-thumb',
  path: '/api/puterin-thumb',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTapeThumbRoute = ApiTapeThumbRouteImport.update({
  id: '/api/tape-thumb',
  path: '/api/tape-thumb',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramRoute = ApiTelegramRouteImport.update({
  id: '/api/telegram',
  path: '/api/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const VIdRoute = VIdRouteImport.update({
  id: '/v/$id',
  path: '/v/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIdRoute = WatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kategori': typeof KategoriRoute
  '/api/data': typeof ApiDataRoute
  '/api/embed-thumb': typeof ApiEmbedThumbRoute
  '/api/puterin-thumb': typeof ApiPuterinThumbRoute
  '/api/tape-thumb': typeof ApiTapeThumbRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/v/$id': typeof VIdRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kategori': typeof KategoriRoute
  '/api/data': typeof ApiDataRoute
  '/api/embed-thumb': typeof ApiEmbedThumbRoute
  '/api/puterin-thumb': typeof ApiPuterinThumbRoute
  '/api/tape-thumb': typeof ApiTapeThumbRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/v/$id': typeof VIdRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kategori': typeof KategoriRoute
  '/api/data': typeof ApiDataRoute
  '/api/embed-thumb': typeof ApiEmbedThumbRoute
  '/api/puterin-thumb': typeof ApiPuterinThumbRoute
  '/api/tape-thumb': typeof ApiTapeThumbRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/v/$id': typeof VIdRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kategori'
    | '/api/data'
    | '/api/embed-thumb'
    | '/api/puterin-thumb'
    | '/api/tape-thumb'
    | '/api/telegram'
    | '/v/$id'
    | '/watch/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kategori'
    | '/api/data'
    | '/api/embed-thumb'
    | '/api/puterin-thumb'
    | '/api/tape-thumb'
    | '/api/telegram'
    | '/v/$id'
    | '/watch/$id'
  id:
    | '__root__'
    | '/'
    | '/kategori'
    | '/api/data'
    | '/api/embed-thumb'
    | '/api/puterin-thumb'
    | '/api/tape-thumb'
    | '/api/telegram'
    | '/v/$id'
    | '/watch/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KategoriRoute: typeof KategoriRoute
  ApiDataRoute: typeof ApiDataRoute
  ApiEmbedThumbRoute: typeof ApiEmbedThumbRoute
  ApiPuterinThumbRoute: typeof ApiPuterinThumbRoute
  ApiTapeThumbRoute: typeof ApiTapeThumbRoute
  ApiTelegramRoute: typeof ApiTelegramRoute
  VIdRoute: typeof VIdRoute
  WatchIdRoute: typeof WatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategori': {
      id: '/kategori'
      path: '/kategori'
      fullPath: '/kategori'
      preLoaderRoute: typeof KategoriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data': {
      id: '/api/data'
      path: '/api/data'
      fullPath: '/api/data'
      preLoaderRoute: typeof ApiDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/embed-thumb': {
      id: '/api/embed-thumb'
      path: '/api/embed-thumb'
      fullPath: '/api/embed-thumb'
      preLoaderRoute: typeof ApiEmbedThumbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/puterin-thumb': {
      id: '/api/puterin-thumb'
      path: '/api/puterin-thumb'
      fullPath: '/api/puterin-thumb'
      preLoaderRoute: typeof ApiPuterinThumbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tape-thumb': {
      id: '/api/tape-thumb'
      path: '/api/tape-thumb'
      fullPath: '/api/tape-thumb'
      preLoaderRoute: typeof ApiTapeThumbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram': {
      id: '/api/telegram'
      path: '/api/telegram'
      fullPath: '/api/telegram'
      preLoaderRoute: typeof ApiTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$id': {
      id: '/v/$id'
      path: '/v/$id'
      fullPath: '/v/$id'
      preLoaderRoute: typeof VIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$id': {
      id: '/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof WatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KategoriRoute: KategoriRoute,
  ApiDataRoute: ApiDataRoute,
  ApiEmbedThumbRoute: ApiEmbedThumbRoute,
  ApiPuterinThumbRoute: ApiPuterinThumbRoute,
  ApiTapeThumbRoute: ApiTapeThumbRoute,
  ApiTelegramRoute: ApiTelegramRoute,
  VIdRoute: VIdRoute,
  WatchIdRoute: WatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
